name = "11ty-microfeed-site"
compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2025-06-06"

[assets]
directory = "./_site"
not_found_handling = "404-page"
html_handling = "auto-trailing-slash"

[build]
command = "npm run build"

[vars]
MICROFEED_JSON_URL = "https://mn-microfeed.pages.dev/json/"